### ISSUE TITLE
Unable to paste password in ICICI Internet Banking Website

### ISSUE THREAD

**Issue by senguttuvang** [jswanner/DontF-WithPaste#135] opened 2024-07-29 10:52 UTC
I think I used to paste the password successfully earlier but it seems to broke. Pasting the password appears to paste only one character, I don't know what. It used to work with 1password password fill. Now, that too is broken, I don't whether any correlation between them. I have posted a loom video.

https://infinity.icicibank.com/corp/AuthenticationController?FORMSGROUP_ID__=AuthenticationFG&__START_TRAN_FLAG__=Y&FG_BUTTONS__=LOAD&ACTION.LOAD=Y&AuthenticationFG.LOGIN_FLAG=1&BANK_ID=ICI&ITM=nli_personalb_personal_login_btn&_gl=1*30xkeg*_ga*MTgzMDcxOTY5Ni4xNjIwMDM5NDU0*_ga_SKB78GHTFV*MTYyODIzNDM4NC43Ny4xLjE2MjgyMzQ1MDQuMjc.&_ga=2.92094746.1084279428.1697432242-1973315115.1690798212&_gac=1.213008672.1697523963.EAIaIQobChMI-7jpvrn8gQMVt6lmAh1nywMHEAAYASAAEgKBxfD_BwE?ITM=nli_personalb_personal_login_btn

https://www.loom.com/share/f77739dd503a4259b7500343a0732ea0

**Comment by jswanner** [comment] 2024-07-31 00:45
@senguttuvang, this is a duplicate of #134. Please see [my response](https://github.com/jswanner/DontF-WithPaste/issues/134#issuecomment-2259427495) there.

**Closed by jswanner** 2024-07-31 00:45 UTC
